// console.log("mithilesh kumar")
// alert("welcome to javascript code ! ");

// let Name = "mithilesh kumar !";
// let Age = 19;

// console.log("your name is =",Name)
// console.log("your age is =",Age)

// const Name = "mithilesh kumar !";
// const Age = 19;

// console.log("your name is =", Name)
// console.log("your age is =",Age)

// var Name = "mithilesh kumar !";
// var Age = 19;

// console.log("your name is =", Name)
// console.log("your age is =",Age)

// var a = 18
// var b = 20
//  a = 25  //allowed
// console.log(a)

// a = 10

// let b = 20
// let a = 12  // not allowed
// console.log(a)

// IN CONST VARIABLE VALUED ARE FIXED YOU CANNOT CHANGE VALUE

// const a = 8924

// console.log(a)
// // OR
// const pi = 3.14;

// console.log(pi)

// THIS ALL EXAMPLE OF PRIMITVE DATA TYPE IN JS 

// 1. Number -: Used for numbers (integer or decimal)

// let a = 19;
// let b = 20;
// console.log(typeof a,"=value of a =",a,typeof b,"=value of b =",b)

// console.log(a)
// console.log(b)
// console.log(typeof a)
// console.log(typeof b)


// 2. String are Used for text in double queto

// let Name = "mithilesh kumar! ";

// console.log("Name is =",Name)
// console.log("The type of name =",typeof Name)

// 3. Boolean variable are used to True or False value

// let isstudent = false
// console.log(isstudent)

// another
// let a = 10;
// let b = 14;
// console.log(a<b); 

// another one 
// let marks = 85;

// if(marks === 8){
//     console.log("first div")
// }else{
//     console.log("fail")
// }

// 4. Undefined  Variable declared but no value assigned

// let n;
// console.log(typeof n)

// var n;
// console.log(n);

// 5.Null  Empty or no value (intentional)

// let n = null;
// console.log(n)

// 6. BigInt are used for Very large (int/ decimal.. ect) numbers

// let big = 875438278939898977648376734657346573467467468734683465874684668456834378793948495784758478n;
// console.log(typeof big,big);


// examplpe for additions/sub/mul/..ect using BigInt variable data type 


// let a = 737736737367376376373n;
// let b = 10;
// console.log(typeof a, a+BigInt(b));
// console.log(typeof b,b)

// console.log(typeof a, a-BigInt(b));
// console.log(typeof a, a*BigInt(b));
// console.log(typeof a, a/BigInt(b));
// console.log(typeof a, a%BigInt(b));

// 7. Symbol datatype are used to  Unique value (mostly advanced use)
// let id_1 = 123;
// let id_2 = 143;
// console.log(id_1 === id_2);


// let id_1 = Symbol('mithilesh')
// let id_2 = id_1;
// id_2 =  Symbol('mithileshh')

// console.log(id_1 === id_2);